# Nazwa serwisu
name: echo

# Parametry 
procman:
  java:
    vmpath: /usr/bin/java
    debug: true
    memory:
      min: 1234m
      max: 1234m
      meta: 1234m
    gc: g1
    classpath: 
      - path
      - path*
      - some.jar
    sysprops:
      - pl.test=true
      - awt.headless=1
    main: some.main.class.Main
    args: ['a','b','c','d']
    streamout: /tmp/out
     
