# Nazwa serwisu
name: echo

# Parametry 
procman:
  java:
    vmpath: /usr/bin/java
    debug: false
    memory:
      min: 128m
      max: 256m
      meta: 128m
    gc: g1
    classpath: 
      - java_lib/*.jar
      - java_app/*
    sysprops:
      - pl.test.grabojan=true
      - java.awt.headless=true
    main: pl.grabojan.camel_echo.MainApp
    #args: ['a']
    streamout: /tmp/out$$
     
