# Nazwa serwisu
name: echo

# Parametry 
procman:
  java:
    vmpath: /usr/bin/java
    debug: false
    memory:
      min: 128m
      max: 256m
      meta: 128m
    gc: g1
    classpath: 
      - "*.jar"
    sysprops:
      - pl.test=true
      - awt.headless=1
    main: program1.Main
    args: ['a']
    streamout: /tmp/out$$
     
